import {Query,type QuerySpec} from '../../shared/query';import{schema,jsonFields}from'./schema';
export type SQL={sql:(q:string,args?:any[])=>Promise<{rows:any[]}>;batch:(s:{sql:string,args?:any[]}[],mode?:'read'|'write')=>Promise<any>};
export type Identity={userId:string;email?:string;master:boolean;academyId?:string;role?:string};
const q=(s:string)=>'"'+s+'"';const val=(v:any)=>typeof v==='boolean'?Number(v):v!==null&&typeof v==='object'?JSON.stringify(v):v??null;
const writers:Record<string,string[]>={academy:['admin'],academy_user:['admin'],team_member:['admin'],plan:['admin'],schedule:['admin','professor'],student:['admin','recepcao'],lead:['admin','recepcao'],financial:['admin'],checkin:['admin','recepcao','professor','personal']};
export function decode(t:string,r:any){return Object.fromEntries(Object.entries(r).map(([k,v])=>{if(schema[t]?.[k]==='BOOLEAN')return[k,v===true||v===1||v==='1'];if(schema[t]?.[k]==='REAL'&&v!==null)return[k,Number(v)];if(jsonFields.has(k)&&typeof v==='string'){try{return[k,JSON.parse(v)]}catch{}}return[k,v]}))}
export class Database{
 constructor(public sql:SQL,public identity:Identity){}from(table:string){return new Query(table,s=>this.execute(s))}
 async scope(t:string,write:boolean){const u=this.identity;if(!schema[t]||['users','profiles','user_roles','template_owner'].includes(t))throw Error('Tabela indisponível');if(!u.userId)throw Error('Autenticação necessária');if(t==='app_config'){if(!u.master)throw Error('Acesso restrito');return{clause:'1=1',args:[]}}
 if(u.master){if(u.academyId&&t!=='academy')return{clause:'academy_id=?',args:[u.academyId]};return{clause:'1=1',args:[]}};if(!u.academyId)throw Error('Academia não encontrada');const ac=(await this.sql.sql('SELECT status,trial_ate FROM academy WHERE id=?',[u.academyId])).rows[0];if(!ac||['blocked','inactive','suspended'].includes(ac.status)||ac.status==='trial'&&ac.trial_ate&&ac.trial_ate<new Date().toISOString().slice(0,10))throw Error('Academia suspensa; fale com o administrador');
 if(write&&!writers[t]?.includes(u.role||''))throw Error('Permissão insuficiente');if(!write&&['financial','academy_user'].includes(t)&&u.role!=='admin')throw Error('Permissão insuficiente');return{clause:(t==='academy'?'id':'academy_id')+'=?',args:[u.academyId]}}
 async execute(input:QuerySpec):Promise<any>{try{const s=structuredClone(input),t=s.table,write=s.action!=='select';if(!['select','insert','update','delete'].includes(s.action))throw Error('Operação inválida');const col=(k:string)=>{if(!schema[t]?.[k])throw Error('Coluna inválida');return q(k)};const scope=await this.scope(t,write),args:any[]=[...scope.args],where=[scope.clause];if(!Array.isArray(s.filters)||s.filters.length>30)throw Error('Filtro inválido');
 for(const f of s.filters){const k=col(f.key);if(f.op==='in'){if(!Array.isArray(f.value)||f.value.length>1000)throw Error('Filtro inválido');where.push(f.value.length?k+' IN ('+f.value.map(()=>'?').join(',')+')':'0=1');args.push(...f.value.map(val));continue}if(f.op==='notnull'){where.push(k+' IS NOT NULL');continue}const op:Record<string,string>={eq:'=',neq:'!=',gt:'>',gte:'>=',lt:'<',lte:'<=',is:'IS',ilike:'LIKE'};if(!op[f.op])throw Error('Operador inválido');where.push(k+' '+op[f.op]+' ?');args.push(val(f.value))}
 const clause=where.join(' AND '),limit=Math.min(5000,Math.max(0,Number(s.limit??1000))),offset=Math.max(0,Number(s.offset??0));if(!Number.isInteger(limit)||!Number.isInteger(offset))throw Error('Paginação inválida');const selected=s.columns==='*'||!s.columns?null:s.columns.split(',').map(x=>x.trim());selected?.forEach(col);let rows:any[]=[],count=0;
 if(!write){count=Number((await this.sql.sql('SELECT COUNT(*) AS total FROM '+q(t)+' WHERE '+clause,args)).rows[0]?.total||0);if(!s.head)rows=(await this.sql.sql('SELECT * FROM '+q(t)+' WHERE '+clause+(s.orders?.length?' ORDER BY '+s.orders.map(o=>col(o.key)+(o.ascending?' ASC':' DESC')).join(','):'')+' LIMIT ? OFFSET ?',[...args,limit,offset])).rows}
 else{if(s.action!=='insert'&&!s.filters.length)throw Error('Alteração exige filtro explícito');if(t==='app_config')throw Error('Configuração protegida');if(t==='academy'&&s.action==='insert')throw Error('Use o cadastro de academia');if(t==='academy_user')throw Error('Gerencie acesso em Equipe');
 if(s.action==='delete'){if(['academy','financial','checkin'].includes(t))throw Error('Registro protegido; altere o status');rows=(await this.sql.sql('DELETE FROM '+q(t)+' WHERE '+clause+' RETURNING *',args)).rows}
 else{const payloads=Array.isArray(s.payload)?s.payload:[s.payload];if(payloads.length!==1)throw Error('Salve um registro por vez');const raw=payloads[0];if(!raw||typeof raw!=='object')throw Error('Dados inválidos');const row={...raw};Object.keys(row).forEach(col);const old=s.action==='update'?(await this.sql.sql('SELECT * FROM '+q(t)+' WHERE '+clause,args)).rows:[];if(old.length>1)throw Error('Atualize um registro por vez');if(s.action==='update'&&!old.length)return{data:[],error:null,count:0};if(s.action==='update'){delete row.id;delete row.created_at;delete row.academy_id;if(schema[t].updated_at)row.updated_at=new Date().toISOString()}
 if(!this.identity.master){if(t==='academy'&&Object.keys(row).some(k=>!['name','slug','cnpj','telefone','email','endereco','cor_primaria','logo_url','business_hours','capacity_per_class','updated_at'].includes(k)))throw Error('Campo protegido');if(t!=='academy'&&s.action==='insert'){if(row.academy_id&&row.academy_id!==this.identity.academyId)throw Error('Academia inválida');row.academy_id=this.identity.academyId}}
 const merged={...(old[0]||{}),...row};if(t!=='academy'&&!(await this.sql.sql('SELECT id FROM academy WHERE id=?',[merged.academy_id])).rows.length)throw Error('Academia inválida');
 for(const k of ['amount','price','valor_mensal','duration_months','max_capacity','capacity_per_class','total_checkins'])if(row[k]!=null&&(!Number.isFinite(Number(row[k]))||Number(row[k])<0||Number(row[k])>1e7))throw Error('Valor inválido: '+k);
 if(['plan','schedule','student','team_member'].includes(t)&&(!String(merged.name||'').trim()||String(merged.name).length>200))throw Error('Nome inválido');
 if(t==='team_member'){if(!['admin','professor','recepcao','personal'].includes(merged.role||'professor'))throw Error('Função inválida');row.email=String(merged.email||'').trim().toLowerCase();if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(row.email))throw Error('Email inválido');const ac=(await this.sql.sql('SELECT owner_email FROM academy WHERE id=?',[merged.academy_id])).rows[0];if(old[0]&&String(old[0].email).toLowerCase()===String(ac.owner_email).toLowerCase())throw Error('Administrador proprietário protegido')}
 if(t==='plan'&&(!Number.isInteger(Number(merged.duration_months??1))||Number(merged.duration_months??1)<1))throw Error('Duração inválida');
 if(t==='schedule'&&(!Number.isInteger(Number(merged.day_of_week))||merged.day_of_week<0||merged.day_of_week>6||!/^([01]\d|2[0-3]):[0-5]\d(:00)?$/.test(merged.start_time)||!/^([01]\d|2[0-3]):[0-5]\d(:00)?$/.test(merged.end_time)||merged.end_time<=merged.start_time||Number(merged.max_capacity??20)<1))throw Error('Horário inválido');
 if(t==='student'&&merged.plan_id){const p=(await this.sql.sql('SELECT name FROM plan WHERE id=? AND academy_id=?',[merged.plan_id,merged.academy_id])).rows[0];if(!p)throw Error('Plano fora da academia');row.plan_name=p.name}
 if(t==='checkin'){if(s.action!=='insert')throw Error('Check-in não pode ser alterado');const st=(await this.sql.sql('SELECT name,status,ativo FROM student WHERE id=? AND academy_id=?',[merged.student_id,merged.academy_id])).rows[0];if(!st||!Number(st.ativo)||st.status==='blocked')throw Error('Aluno não autorizado');row.student_name=st.name;if(!/^\d{4}-\d{2}-\d{2}$/.test(merged.date)||!/^([01]\d|2[0-3]):[0-5]\d(:[0-5]\d)?$/.test(merged.time))throw Error('Data inválida')}
 if(t==='financial'){if(!['receita','despesa'].includes(merged.type||'receita')||!['pendente','pago','cancelado'].includes(merged.status||'pendente'))throw Error('Status financeiro inválido');if(!/^\d{4}-\d{2}-\d{2}$/.test(merged.date))throw Error('Data inválida');row.amount=Math.round(Number(merged.amount)*100)/100}
 if(s.action==='insert'&&!row.id)row.id=crypto.randomUUID();const keys=Object.keys(row),params=keys.map(k=>val(row[k]));rows=(await this.sql.sql(s.action==='update'?'UPDATE '+q(t)+' SET '+keys.map(k=>col(k)+'=?').join(',')+' WHERE '+clause+' RETURNING *':'INSERT INTO '+q(t)+' ('+keys.map(col).join(',')+') VALUES ('+keys.map(()=>'?').join(',')+') RETURNING *',s.action==='update'?[...params,...args]:params)).rows
 }count=rows.length}
 const data=rows.map(r=>{const d=decode(t,r);if(t==='student'&&!this.identity.master&&!['admin','professor','personal'].includes(this.identity.role||''))delete d.medical_notes;return selected?Object.fromEntries(selected.map(k=>[k,d[k]])):d});if(s.cardinality==='one'&&data.length!==1)throw Error('Registro não encontrado');return{data:s.head?null:s.cardinality?data[0]??null:data,error:null,count}
 }catch(e:any){return{data:null,error:{message:e.message},count:0}}}
}
