import{test}from'node:test';import assert from'node:assert/strict';import{DatabaseSync}from'node:sqlite';import{readFileSync}from'node:fs';import{Database}from'../server/native/database';import{createAcademy}from'../server/native/academy';import{publicBooking}from'../server/native/public-booking';import{ownerEligible}from'../server/native/owner';
function fixture(){const db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON;');for(const f of ['schema.sql','bootstrap.sql'])db.exec(readFileSync(new URL('../scripts/native/'+f,import.meta.url),'utf8'));db.exec("CREATE TABLE users(id TEXT PRIMARY KEY,email TEXT,email_verified INTEGER); INSERT INTO academy(id,name,slug,status,owner_email) VALUES('a','A','academy-a','active','a@example.test'),('b','B','academy-b','active','b@example.test'); INSERT INTO plan(id,academy_id,name,price) VALUES('pa','a','Mensal',89),('pb','b','Mensal B',99); INSERT INTO student(id,academy_id,name,cpf) VALUES('sa','a','Aluno A','123'),('sb','b','Aluno B','456');");const sql={sql:async(q:string,args:any[]=[])=>({rows:db.prepare(q).all(...args)}),batch:async(st:any[])=>{db.exec('BEGIN');try{const out=st.map(s=>({rows:db.prepare(s.sql).all(...(s.args||[]))}));db.exec('COMMIT');return out}catch(e){db.exec('ROLLBACK');throw e}}};const identity={userId:'ua',email:'a@example.test',master:false,academyId:'a',role:'admin'};return{db,sql,identity,app:new Database(sql,identity)}}
test('Leitura e escrita ficam na academia autorizada; Master selecionado também',async()=>{const x=fixture();assert.equal((await x.app.from('student').select('*')).data.length,1);assert.equal((await x.app.from('student').update({name:'invade'}).eq('id','sb')).count,0);assert.ok((await x.app.from('student').insert({academy_id:'b',name:'Hack'})).error);const master=new Database(x.sql,{...x.identity,master:true});assert.equal((await master.from('student').select('*')).data.length,1)});
test('Anônimo e promoção por CRUD bloqueados',async()=>{const x=fixture();assert.ok((await new Database(x.sql,{userId:'',master:false}).from('student').select('*')).error);assert.ok((await x.app.from('user_roles').insert({user_id:'ua',role:'super_admin'})).error);assert.ok((await x.app.from('app_config').select('*')).error)});
test('Plano de outra academia rejeitado pelo backend e SQL',async()=>{const x=fixture();assert.ok((await x.app.from('student').update({plan_id:'pb'}).eq('id','sa')).error);assert.throws(()=>x.db.exec("UPDATE student SET plan_id='pb' WHERE id='sa'"),/fora da academia/);const r=await x.app.from('student').update({plan_id:'pa',plan_name:'adulterado'}).eq('id','sa');assert.equal(r.data[0].plan_name,'Mensal')});
test('Check-in exige aluno da academia, ativo, com um registro por dia',async()=>{const x=fixture();const p={academy_id:'a',student_id:'sa',student_name:'Falso',date:'2026-09-17',time:'10:00'};assert.equal((await x.app.from('checkin').insert(p)).data[0].student_name,'Aluno A');assert.ok((await x.app.from('checkin').insert(p)).error);assert.ok((await x.app.from('checkin').insert({...p,student_id:'sb'})).error);x.db.exec("UPDATE student SET status='blocked' WHERE id='sa'");assert.ok((await x.app.from('checkin').insert({...p,date:'2026-09-18'})).error)});
test('Financeiro centavos, negativo e vínculo cruzado; marcar pago é idempotente',async()=>{const x=fixture();const r=await x.app.from('financial').insert({academy_id:'a',amount:89.909,date:'2026-09-17',student_id:'sa'});assert.equal(r.data[0].amount,89.91);for(let n=0;n<2;n++)assert.equal((await x.app.from('financial').update({status:'pago'}).eq('id',r.data[0].id)).error,null);assert.equal(x.db.prepare('SELECT COUNT(*) AS n FROM financial').get().n,1);assert.ok((await x.app.from('financial').insert({academy_id:'a',amount:-1,date:'2026-09-17'})).error);assert.ok((await x.app.from('financial').insert({academy_id:'a',student_id:'sb',amount:99,date:'2026-09-17'})).error)});
test('Professor não muda finanças, papel nem cobrança; owner protegido',async()=>{const x=fixture();const p=new Database(x.sql,{...x.identity,role:'professor'});assert.ok((await p.from('financial').select('*')).error);assert.ok((await p.from('team_member').insert({name:'x',email:'x@y.com',role:'admin'})).error);assert.ok((await x.app.from('academy').update({valor_mensal:0}).eq('id','a')).error)});
test('Cadastro público não expõe alunos nem owner e rejeita plano/horário cruzado',async()=>{const x=fixture();const c=await publicBooking(x,{action:'catalog',slug:'academy-a'});assert.equal(c.academy.owner_email,undefined);assert.equal(c.plans.length,1);await assert.rejects(publicBooking(x,{action:'lead',slug:'academy-a',type:'interesse_plano',name:'Teste QA',phone:'51999999999',plan_id:'pb'}),/Plano inválido/);await assert.rejects(publicBooking(x,{action:'lead',slug:'academy-a',type:'aula_experimental',name:'Teste QA',phone:'51999999999',schedule_id:'missing'}),/Horário inválido/)});
test('Lead público repetido não duplica e não cria matrícula/pagamento sozinho',async()=>{const x=fixture();const d={action:'lead',slug:'academy-a',type:'interesse_plano',name:'Teste QA',phone:'51999999999',plan_id:'pa'};await publicBooking(x,d);assert.equal((await publicBooking(x,d)).duplicate,true);assert.equal(x.db.prepare('SELECT count(*) n FROM lead').get().n,1);assert.equal(x.db.prepare('SELECT count(*) n FROM financial').get().n,0)});
test('Cadastro academia atomicamente cria proprietário e planos; rollback',async()=>{const x=fixture();const c=await createAcademy({...x,identity:{userId:'new',email:'new@example.test',master:false},emailVerified:true},{name:'Nova academia',slug:'nova',plans:[{name:'Mensal',price:100,duration_months:1}]});assert.equal(x.db.prepare('SELECT count(*) n FROM plan WHERE academy_id=?').get(c.academy_id).n,1);await assert.rejects(createAcademy({...x,emailVerified:true,identity:{userId:'new2',email:'new2@example.test',master:false}},{name:'Falha',slug:'nova'}));assert.equal(x.db.prepare('SELECT count(*) n FROM academy').get().n,3)});
test('Owner exige projeto correto e email verificado',async()=>{const x=fixture();x.db.exec("INSERT INTO users VALUES('ua','a@example.test',0)");const env={BLINK_PROJECT_ID:'current',OWNER_PROJECT_ID:'current',OWNER_EMAIL:'a@example.test'};assert.equal(await ownerEligible({userId:'ua',email:'a@example.test'},env,x.sql),false);x.db.exec("UPDATE users SET email_verified=1 WHERE id='ua'");assert.equal(await ownerEligible({userId:'ua',email:'a@example.test'},env,x.sql),true);assert.equal(await ownerEligible({userId:'ua',email:'a@example.test'},{...env,OWNER_PROJECT_ID:'original'},x.sql),false)});
test('Busca nome e CPF não amplia escopo e suspensa bloqueia',async()=>{const x=fixture();assert.equal((await x.app.from('student').select('*').ilike('name','%Aluno%')).data.length,1);assert.equal((await x.app.from('student').select('*').ilike('cpf','%456%')).data.length,0);x.db.exec("UPDATE academy SET status='blocked' WHERE id='a'");assert.ok((await x.app.from('student').select('*')).error)});
