from pathlib import Path
import sqlite3,json
root=Path(__file__).resolve().parents[2]; statements=[]
for name in ['schema.sql','bootstrap.sql']:
 buf=''
 for line in (root/'scripts/native'/name).read_text().splitlines(True):
  buf+=line
  if sqlite3.complete_statement(buf):statements.append({'sql':buf.strip()});buf=''
 if buf.strip():raise RuntimeError('SQL incompleto: '+name)
(root/'server/native/bootstrap.ts').write_text('''// Generated by scripts/native/generate-bootstrap.py. Keep each trigger whole.
const statements='''+json.dumps(statements,ensure_ascii=False)+''';
const ready=new Map<string,Promise<void>>();
export async function ensureDatabase(sql:any,projectId:string){
 if(!ready.has(projectId))ready.set(projectId,(async()=>{
  const check=await sql.sql("SELECT name FROM sqlite_master WHERE type='trigger' AND name='gymboss_schema_v1'");
  if(!check.rows.length)await sql.batch(statements,'write');
 })().catch(e=>{ready.delete(projectId);throw e}));
 await ready.get(projectId);
}
''')
print('Bootstrap:',len(statements),'instruções completas')
